import { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import { Box } from '@mui/material';

import { Navbar, Sidebar } from '../exports';
import { DrawerHeader } from '../styles/layout';

interface Props {
	children: JSX.Element[] | JSX.Element;
}

const Layout: NextPage<Props> = ({ children }) => {
	const [open, setOpen] = useState(true);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Box sx={{ display: 'flex' }}>
				<Navbar open={open} setOpen={setOpen} />
				<Sidebar open={open} setOpen={setOpen} />
				<Box component='main' sx={{ flexGrow: 1, p: 3, height: '200vh' }}>
					<DrawerHeader
						style={{
							minHeight: 50,
						}}
					/>
					{children}
				</Box>
			</Box>
		</>
	);
};

export default Layout;
